name: Build Glass Browser
on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permite executar manualmente
jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # Removido cache: 'npm' temporariamente
        
    - name: Instalar dependências
      run: npm install
      
    - name: Build aplicativo para Windows
      run: npm run build-win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact Windows
      uses: actions/upload-artifact@v4
      with:
        name: glass-browser-windows
        path: |
          dist/*.exe
          dist/*.msi
          dist/*.appx
        retention-days: 30
  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # Removido cache: 'npm' temporariamente
        
    - name: Instalar dependências
      run: npm install
      
    - name: Build aplicativo para macOS
      run: npm run build-mac
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact macOS
      uses: actions/upload-artifact@v4
      with:
        name: glass-browser-macos
        path: |
          dist/*.dmg
          dist/*.zip
        retention-days: 30
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # Removido cache: 'npm' temporariamente
        
    - name: Instalar dependências do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libgtk-3-dev libgbm-dev
        
    - name: Instalar dependências npm
      run: npm install
      
    - name: Build aplicativo para Linux
      run: npm run build-linux
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact Linux
      uses: actions/upload-artifact@v4
      with:
        name: glass-browser-linux
        path: |
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
        retention-days: 30
  # Job para criar release automático quando push de tag
  release:
    needs: [build-windows, build-mac, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Download todos os artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        
    - name: Criar Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/glass-browser-windows/*
          ./artifacts/glass-browser-macos/*
          ./artifacts/glass-browser-linux/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
